CREATE OR ALTER TRIGGER TPERS_Filas_U
ON PERS_Filas
FOR UPDATE
AS 
BEGIN
    IF EXISTS(SELECT 1 FROM inserted) BEGIN
        IF UPDATE(IdFila)
        BEGIN
            PRINT 'IMPOSIBLE ACTUALIZAR FILA'
            ROLLBACK TRAN
            RETURN
        END
    END
END
GO

ALTER TABLE PERS_Filas ENABLE TRIGGER TPERS_Filas_U
GO